# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{revisor_client}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Mikhail Lapshin"]
  s.date = %q{2011-04-10}
  s.description = %q{}
  s.email = %q{sotakone@sotakone.com}
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/revisor.rb",
    "lib/revisor/client.rb",
    "lib/revisor/client/session.rb",
    "lib/revisor/client/tab.rb",
    "revisor_client.gemspec",
    "test/session_tab_test.rb",
    "test/session_test.rb",
    "test/test_helper.rb",
    "test/test_pages/send_key_event.html",
    "test/test_pages/send_mouse_click_event.html",
    "test/test_pages/send_mouse_move_event.html"
  ]
  s.homepage = %q{http://github.com/sotakone/revisor/}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{Ruby helper library for Revisor browser}
  s.test_files = [
    "test/session_tab_test.rb",
    "test/session_test.rb",
    "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

